urlshortener/shorterurl/urls.py
from django.urls import include, path
from shorterurl import views

app_name = 'shorterurl'

urlpatterns = [
    path('', views.index, name='index'),
    path('<short_id>', views.redirect_original, name='redirect'),
    path('makeshort/', views.shorten_url, name='shortenurl'),
]

urlshortener/urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shorterurl.urls', namespace='shorterurl'))
]

urlshortener/shorterurl/models.py
from django.db import models

# Create your models here.
class Urls(models.Model):
    short_id = models.SlugField(max_length=6, primary_key=True)
    http_url = models.URLField(max_length=200)

    def __str__(self):
        return self.http_url

urlshortener/shorterurl/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
import random, string, json
from shorterurl.models import Urls
from django.template.context_processors import csrf
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse

def index(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('shorterurl/index.html', c)


def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id)
    url.save()
    return HttpResponseRedirect(url.http_url)


def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        short_id = get_short_code()
        b = Urls(http_url=url, short_id=short_id)
        b.save()
        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + short_id
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    return HttpResponse(json.dumps({"error": "error ocurs"}), content_type="application/json")


def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.ascii_lowercase + string.digits
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        if not Urls.objects.filter(pk=short_id).exists():
            return short_id

urlshortener/shorterurl/templates/shorterurl/base.html
<!DOCTYPE html>
<html>
<head>
 {% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" type="text/css" href="{% static 'shortenersite/css/custom.css' %}" />
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script type="text/javascript">
 $(function() {
 $('#submitButton').click(function() {
 $.ajax({
 type: "POST",
 url: "/makeshort/",
 data: {
 'url' : $('#url').val(),
 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
 },
 success: returnSuccess,
 dataType: 'json'
 });
 });
});

function returnSuccess(data, textStatus, jqXHR) {
 if(data.url) {
 $('#url-result').text(data.url);
 $('#url').val("");
 } else {
 $('#url-result').text("Do not submit blank.");
 }

}
</script>
<body>
<div id="wrap">
<header>
 <h1><a href="{% url 'shorterurl:index' %}">URL Shortner</a></h1>
</header>

<div id="content">
{% block content %}

{% endblock %}
</div>
</div>
</body>
</html>

urlshortener/shorterurl/templates/shorterurl/index.html
{% extends "shorterurl/base.html" %}

{% block title %}Make your URL shorter!{% endblock %}

{% block content %}

<div class="panel panel-default">
 <div class="panel-body">
 <div class="col-sm-9">
 <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.facebook.com" />
 </div>
 <div class="col-sm-3">
 {% csrf_token %}
 <button id="submitButton" class="btn btn-primary">Submit</button></p>
 </div>
 </div>
 <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
</div>
{% endblock %}